[package]
name = "deezchatz-cli"
version = "0.1.0"
description = "CLI for the deezchatz chat ecosystem"
authors = ["debarkamondal <debarkamondal@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
tokio = { version = "1.35", features = ["full"] }
deezchatz-sdk-rust = { path = "../deezchatz-sdk" }
rusqlite = { version = "0.31", features = ["bundled-sqlcipher"] }
keyring = { version = "3", features = ["sync-secret-service"] }
directories = "5"
open = "5"
tiny_http = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
async-trait = "0.1"
url = "2"
rand = "0.8"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }

[build-dependencies]
clap = { version = "4", features = ["derive"] }
clap_mangen = "0.2"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
